# Use uma imagem Node.js oficial e leve
FROM node:18-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Copia o package.json (e package-lock.json se existir)
COPY package*.json ./

# Instala somente as dependências de produção
RUN npm install --omit=dev

# Copia o resto do código (o index.js)
COPY . .

# Expõe a porta que o app vai rodar
EXPOSE 3000

# Comando padrão para iniciar o app (O CORRETO)
CMD [ "npm", "start" ]
